# Generated by Django 4.0.4 on 2022-04-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='finish_date_deadline',
        ),
    ]
